### ISSUE TITLE
Missing information that braze integration will need to be updated when migrating to v4

### ISSUE THREAD

**Issue by pm0u** [mparticle-integrations/mparticle-javascript-integration-braze#43]
You should mention that analytics will break unless the steps in this random help article are taken:

https://support.mparticle.com/hc/en-us/articles/18305651289869-mParticle-Braze-V4-Web-SDK-Setup

**Comment by rmi22186** [comment]
@pm0u - Thanks for catching that oversight!  Our primary docs page has been clarified to the below to make it more explicit:

<img width="827" alt="image" src="https://github.com/mparticle-integrations/mparticle-javascript-integration-braze/assets/5377436/019c96bf-f4af-418f-8803-6a97c32fd34d">

The same changes have been made to the README in this repo.  As this is a docs related issue, I am closing this issue given the updates we just made.
