### ISSUE TITLE
Publish an ESM compatible build

### ISSUE THREAD

**Issue by dasco144** [mparticle-integrations/mparticle-javascript-integration-braze#49]
When building in an Angular project, you get the following warning:

```
Warning: braze.service.ts depends on '@mparticle/web-braze-kit'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Is there a plan to publish an ESM distribution of `@mparticle/web-braze-kit`?

**Comment by rmi22186** [comment]
Hi @dasco144 - there is an ESM build now. Apologies for the delay.  It is available on our latest version 5 update for Braze.  Please see our docs for how to update and if you need to make any other additional code changes depending on if you are currently on version 3 or 4 from the mParticle UI settings.  

https://docs.mparticle.com/integrations/braze/event/#opt-in-to-braze-sdk-version-5

Let me know if you have any questions. For now I will be closing this ticket as resolved.

**Comment by dasco144** [comment]
That's great. 
Thank you @rmi22186 🚀

I'll reach out if I have any further questions
